#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0

import argparse
import hashlib
import json
import pathlib
import re
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
SCHEMAS = (
    (ROOT / "protocol" / "schema" / "transport.json",
     ROOT / "protocol" / "generated" / "include" / "kobox2" / "protocol_layout.h",
     "KB2_PROTOCOL", "KOBOX2_PROTOCOL_LAYOUT_H"),
    (ROOT / "protocol" / "schema" / "closure.json",
     ROOT / "protocol" / "generated" / "include" / "kobox2" / "closure_layout.h",
     "KB2_CLOSURE", "KOBOX2_CLOSURE_LAYOUT_H"),
)

TYPE_SIZE = {
    "u8": 1,
    "u32": 4,
    "u64": 8,
}

JSON_SAFE_INTEGER_MAX = 9007199254740991


def identifier(value):
    return re.sub(r"[^A-Za-z0-9]", "_", value).upper()


def field_size(type_name):
    match = re.fullmatch(r"(u8|u32|u64)(?:\[(\d+)\])?", type_name)
    if match is None:
        raise ValueError(f"unsupported field type: {type_name}")
    count = int(match.group(2) or "1")
    return TYPE_SIZE[match.group(1)] * count


def validate_canonical_value(value):
    if value is None or isinstance(value, bool):
        return
    if isinstance(value, int):
        if abs(value) > JSON_SAFE_INTEGER_MAX:
            raise ValueError("integer is outside the RFC 8785 exact range")
        return
    if isinstance(value, str):
        try:
            value.encode("ascii")
        except UnicodeEncodeError as error:
            raise ValueError("schema strings must be ASCII") from error
        return
    if isinstance(value, list):
        for element in value:
            validate_canonical_value(element)
        return
    if isinstance(value, dict):
        for key, element in value.items():
            if not isinstance(key, str):
                raise ValueError("schema object keys must be strings")
            validate_canonical_value(key)
            validate_canonical_value(element)
        return
    raise ValueError(f"unsupported schema value: {type(value).__name__}")


def load_schema(schema_path):
    with schema_path.open("r", encoding="utf-8") as source:
        schema = json.load(source)
    if schema.get("spdx") != "MIT":
        raise ValueError("schema SPDX must be MIT")
    if schema.get("byte_order") != "little":
        raise ValueError("only little-endian schemas are supported")
    identity = schema.get("abi_identity", "").encode("ascii")
    if identity != b"dev\0":
        raise ValueError("development ABI identity must be dev\\0")
    if schema.get("digest_algorithm") != "sha256":
        raise ValueError("schema digest must use SHA-256")
    if schema.get("digest_canonicalization") != "RFC8785":
        raise ValueError("schema digest must use RFC 8785 canonicalization")
    validate_canonical_value(schema)

    for structure_name, structure in schema["structures"].items():
        structure_size = structure["size"]
        occupied = [False] * structure_size
        names = set()
        for field in structure["fields"]:
            name = field["name"]
            if name in names:
                raise ValueError(f"duplicate field {structure_name}.{name}")
            names.add(name)
            start = field["offset"]
            end = start + field_size(field["type"])
            if start < 0 or end > structure_size:
                raise ValueError(f"field outside {structure_name}: {name}")
            if any(occupied[start:end]):
                raise ValueError(f"overlapping field in {structure_name}: {name}")
            occupied[start:end] = [True] * (end - start)
        if not all(occupied):
            raise ValueError(f"unassigned bytes in {structure_name}")
    return schema


def render(schema, prefix, guard):
    canonical = json.dumps(schema, sort_keys=True, separators=(",", ":"), ensure_ascii=True)
    digest = hashlib.sha256(canonical.encode("utf-8")).digest()
    digest_lines = []
    for index in range(0, len(digest), 8):
        values = ", ".join(f"0x{value:02x}" for value in digest[index : index + 8])
        if index + 8 < len(digest):
            values += ","
        digest_lines.append(f"        {values} \\")

    lines = [
        "/* SPDX-License-Identifier: MIT */",
        "/* Generated by tools/generate_protocol.py. Do not edit. */",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        f"#define {prefix}_SCHEMA_SHA256_HEX \\",
        f'    "{digest.hex()[:32]}" ' + "\\",
        f'    "{digest.hex()[32:]}"',
        f"#define {prefix}_SCHEMA_DIGEST_SIZE 32u",
        f"#define {prefix}_SCHEMA_SHA256_BYTES \\",
        "    { \\",
        *digest_lines,
        "    }",
        "",
        f"#define {prefix}_ABI_IDENTITY_SIZE 4u",
        f"#define {prefix}_ABI_IDENTITY_BYTES {{0x64, 0x65, 0x76, 0x00}}",
        "",
    ]

    for name, value in schema["constants"].items():
        suffix = "ull" if value > 0xFFFFFFFF else "u"
        lines.append(f"#define {prefix}_{identifier(name)} {value}{suffix}")
    lines.append("")

    for structure_name, structure in schema["structures"].items():
        structure_prefix = f"{prefix}_{identifier(structure_name)}"
        lines.append(f"#define {structure_prefix}_SIZE {structure['size']}u")
        for field in structure["fields"]:
            lines.append(f"#define {structure_prefix}_{identifier(field['name'])}_OFFSET {field['offset']}u")
        lines.append("")

    lines.extend(["#endif", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()

    try:
        rendered = [(output, render(load_schema(schema), prefix, guard))
                    for schema, output, prefix, guard in SCHEMAS]
    except (OSError, ValueError, KeyError, TypeError, json.JSONDecodeError) as error:
        print(f"protocol generation failed: {error}", file=sys.stderr)
        return 1

    if arguments.check:
        try:
            for output, expected in rendered:
                actual = output.read_text(encoding="utf-8")
                if actual != expected:
                    print(f"generated file is stale: {output}", file=sys.stderr)
                    return 1
        except OSError as error:
            print(f"protocol generation check failed: {error}", file=sys.stderr)
            return 1
        return 0

    for output_path, expected in rendered:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with output_path.open("w", encoding="utf-8", newline="\n") as output:
            output.write(expected)
    return 0


if __name__ == "__main__":
    sys.exit(main())
