# SPDX-License-Identifier: Apache-2.0

# These describe the target, not the machine running CMake. Cross toolchains
# supply CMAKE_SYSTEM_NAME / PROCESSOR; configuring never runs target code.
string(TOLOWER "${CMAKE_SYSTEM_NAME}" _kb2_default_os)
string(TOLOWER "${CMAKE_SYSTEM_PROCESSOR}" _kb2_default_arch)
if(_kb2_default_arch STREQUAL "amd64")
    set(_kb2_default_arch x86_64)
endif()
set(KB2_OS_BACKEND "${_kb2_default_os}" CACHE STRING "Native sandbox OS backend")
set(KB2_CPU_ARCH "${_kb2_default_arch}" CACHE STRING "Sandbox CPU architecture")
set_property(CACHE KB2_OS_BACKEND PROPERTY STRINGS linux)
set_property(CACHE KB2_CPU_ARCH PROPERTY STRINGS x86_64)
option(KB2_BUILD_SANDBOX "Build the GPL sandbox foundation as separate targets" ON)

if(KB2_BUILD_SANDBOX)
    set(_kb2_ports "${PROJECT_SOURCE_DIR}/linux-sandbox/kobox")
    foreach(_selector KB2_OS_BACKEND KB2_CPU_ARCH)
        if(NOT "${${_selector}}" MATCHES "^[a-z][a-z0-9_]*$")
            message(FATAL_ERROR "Invalid ${_selector}: ${${_selector}}")
        endif()
    endforeach()
    if(NOT EXISTS "${_kb2_ports}/host/${KB2_OS_BACKEND}/targets.cmake")
        message(FATAL_ERROR "Unsupported OS backend: ${KB2_OS_BACKEND}")
    endif()
    if(NOT EXISTS "${_kb2_ports}/arch/${KB2_CPU_ARCH}/targets.cmake")
        message(FATAL_ERROR "Unsupported CPU architecture: ${KB2_CPU_ARCH}")
    endif()
    if(NOT EXISTS "${_kb2_ports}/arch/${KB2_CPU_ARCH}/os/${KB2_OS_BACKEND}.cmake")
        message(FATAL_ERROR "Unsupported OS/architecture ABI glue: ${KB2_OS_BACKEND}/${KB2_CPU_ARCH}")
    endif()
    if(NOT KB2_OS_BACKEND STREQUAL _kb2_default_os)
        message(FATAL_ERROR "OS backend does not match the target toolchain")
    endif()
    if(NOT KB2_CPU_ARCH STREQUAL _kb2_default_arch)
        message(FATAL_ERROR "CPU architecture does not match the target toolchain")
    endif()
    if(NOT CMAKE_C_COMPILER_ID MATCHES "Clang|GNU")
        message(FATAL_ERROR "The sandbox requires a Clang or GCC target toolchain")
    endif()
    message(STATUS "Sandbox: OS=${KB2_OS_BACKEND}, arch=${KB2_CPU_ARCH}, profile=4KiB/2CPU")
endif()
